price : float=(2.99)
quantity:int = (3)
tax_rate: float = (7.5)
subtotal = (price*quantity)
tax = (subtotal*(tax_rate / 100))
total = (subtotal + tax)
print (f"price of item : ${price}") 
print(f"quantity : {quantity}")
print(f"tax rate : {tax_rate}%" )
print()
print(f"subtotal : ${subtotal:.2f}")
print(f"tax : ${tax:.2f}")
print (f"total : ${total:.2f}")

